server:
    port: 8080

spring:
#    security:
#        client:
#            oauth2:
#                registration:
#                    google:
#                        client-id: ${GOOGLE_CLIENT_ID}
#                        client-secret: ${GOOGLE_CLIENT_SECRET}
#                        redirect-uri: ${URI}/oauth2/callback/{registrationId}
#                        scope: profile,email
#                    github:
#                        client-id: ${GITHUB_CLIENT_ID}
#                        client-secret: ${GITHUB_CLIENT_SECRET}
#                        scope: read:user,user:email
#                    provider:
#                      github:
#                          authorization-uri: https://github.com/login/oauth/authorize
#                          token-uri: https://gihub.com/login/oauth2/access_token
#                          user-info-uri: https://api.github.com/user
    datasource:
        url: ${BASE_URL}
        username: ${BASE_USERNAME}
        password: ${BASE_PASS}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USER}
        password: ${MAIL_PASS}
        properties:
                mail.smtp.auth: true
                mail.smtp.starttls.enable: true

jwt:
    secret: ${JWT_SECRET}
    access-tim e: ${JWT_ACCESS_TIME}
    refresh-time: ${JWT_REFRESH_TIME}