server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:3306/postgres
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
    secret: "qwertyuiopasdfghjklxcvbnm1234567890"
    access-time: 900000
    refresh-time: 604800000