server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:3306/postgres
        username: postgres
        password: 1234
        driver-cllass-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

